version: "3.0"

services:
  backend:
    image: "celiamssd/episen-sca-cme-back"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - './episen-sca-cme-back/dockerlogs:/logs'
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080 || exit 1"]
      timeout: 30s
      interval: 1m
      retries: 3
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.15'
          memory: 128m
        reservations:
          cpus: '0.05'
          memory: 64M

  frontend:
    image: "celiamssd/episen-sca-cme-front"
    restart: always
    ports:
      - "80:80"
    volumes:
      - './episen-sca-cme-front/episen-sca-cme-front/dockerlog:/var/log/nginx'
    healthcheck:
      test: ["CMD", "curl -f http://localhost:80 || exit 1"]
      timeout: 30s
      interval: 1m
      retries: 3
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.15'
          memory: 128m
        reservations:
          cpus: '0.05'
          memory: 64M
